// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Object struct {
	ID         string    `json:"id"`
	ParentHash string    `json:"parent_hash"`
	IsFolder   bool      `json:"is_folder"`
	Metadata   []byte    `json:"metadata"`
	SizeBytes  int64     `json:"size_bytes"`
	CreatedAt  time.Time `json:"created_at"`
}

type ObjectTag struct {
	ObjectID string `json:"object_id"`
	TagHash  string `json:"tag_hash"`
}

type Request struct {
	ID        string       `json:"id"`
	CreatedAt sql.NullTime `json:"created_at"`
}
