// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Object struct {
	ID           string    `json:"id"`
	PrefixHash   string    `json:"prefix_hash"`
	SizeBytes    int64     `json:"size_bytes"`
	UploadStatus string    `json:"upload_status"`
	Metadata     []byte    `json:"metadata"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type ObjectTag struct {
	ObjectID string `json:"object_id"`
	TagHash  string `json:"tag_hash"`
}

type Request struct {
	ID        string       `json:"id"`
	CreatedAt sql.NullTime `json:"created_at"`
}
