// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Orbit struct {
	PersonaID   string    `json:"persona_id"`
	SigningKey  []byte    `json:"signing_key"`
	ExchangeKey []byte    `json:"exchange_key"`
	Metadata    []byte    `json:"metadata"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Request struct {
	ID        string       `json:"id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Ufo struct {
	ID           string    `json:"id"`
	PrefixHash   string    `json:"prefix_hash"`
	SizeBytes    int64     `json:"size_bytes"`
	UploadStatus string    `json:"upload_status"`
	Metadata     []byte    `json:"metadata"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type UfoAccess struct {
	UfoID      string `json:"ufo_id"`
	PersonaID  string `json:"persona_id"`
	WrappedKey []byte `json:"wrapped_key"`
}

type UfoTag struct {
	UfoID   string `json:"ufo_id"`
	TagHash string `json:"tag_hash"`
}
