// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: objects.sql

package database

import (
	"context"
	"time"
)

const createObject = `-- name: CreateObject :exec
INSERT INTO objects (id, parent_hash, is_folder, metadata, size_bytes, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateObjectParams struct {
	ID         string    `json:"id"`
	ParentHash string    `json:"parent_hash"`
	IsFolder   bool      `json:"is_folder"`
	Metadata   []byte    `json:"metadata"`
	SizeBytes  int64     `json:"size_bytes"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) CreateObject(ctx context.Context, arg CreateObjectParams) error {
	_, err := q.db.ExecContext(ctx, createObject,
		arg.ID,
		arg.ParentHash,
		arg.IsFolder,
		arg.Metadata,
		arg.SizeBytes,
		arg.CreatedAt,
	)
	return err
}

const deleteObject = `-- name: DeleteObject :exec
DELETE FROM objects WHERE id = ?
`

func (q *Queries) DeleteObject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteObject, id)
	return err
}

const getObject = `-- name: GetObject :one
SELECT id, parent_hash, is_folder, metadata, size_bytes, created_at FROM objects WHERE id = ?
`

func (q *Queries) GetObject(ctx context.Context, id string) (Object, error) {
	row := q.db.QueryRowContext(ctx, getObject, id)
	var i Object
	err := row.Scan(
		&i.ID,
		&i.ParentHash,
		&i.IsFolder,
		&i.Metadata,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const listObjectsByParent = `-- name: ListObjectsByParent :many
SELECT id, parent_hash, is_folder, metadata, size_bytes, created_at FROM objects WHERE parent_hash = ?
`

func (q *Queries) ListObjectsByParent(ctx context.Context, parentHash string) ([]Object, error) {
	rows, err := q.db.QueryContext(ctx, listObjectsByParent, parentHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Object
	for rows.Next() {
		var i Object
		if err := rows.Scan(
			&i.ID,
			&i.ParentHash,
			&i.IsFolder,
			&i.Metadata,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
