// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: object_tags.sql

package database

import (
	"context"
)

const addObjectTag = `-- name: AddObjectTag :one
INSERT INTO object_tags (object_id, tag_hash)
VALUES (
  ?,
  ?
)
RETURNING object_id
`

type AddObjectTagParams struct {
	ObjectID string `json:"object_id"`
	TagHash  string `json:"tag_hash"`
}

func (q *Queries) AddObjectTag(ctx context.Context, arg AddObjectTagParams) (string, error) {
	row := q.db.QueryRowContext(ctx, addObjectTag, arg.ObjectID, arg.TagHash)
	var object_id string
	err := row.Scan(&object_id)
	return object_id, err
}

const deleteObjectTags = `-- name: DeleteObjectTags :exec
DELETE FROM object_tags WHERE object_id = ?
`

func (q *Queries) DeleteObjectTags(ctx context.Context, objectID string) error {
	_, err := q.db.ExecContext(ctx, deleteObjectTags, objectID)
	return err
}

const getTagsForObject = `-- name: GetTagsForObject :many
SELECT object_id, tag_hash FROM object_tags WHERE object_id = ?
`

func (q *Queries) GetTagsForObject(ctx context.Context, objectID string) ([]ObjectTag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsForObject, objectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ObjectTag
	for rows.Next() {
		var i ObjectTag
		if err := rows.Scan(&i.ObjectID, &i.TagHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
