// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: objects.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createObject = `-- name: CreateObject :one
INSERT INTO objects (
  id,
  prefix_hash,
  size_bytes,
  upload_status,
  metadata,
  created_at,
  updated_at
)
VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
RETURNING id, created_at
`

type CreateObjectParams struct {
	ID           string `json:"id"`
	PrefixHash   string `json:"prefix_hash"`
	SizeBytes    int64  `json:"size_bytes"`
	UploadStatus string `json:"upload_status"`
	Metadata     []byte `json:"metadata"`
}

type CreateObjectRow struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateObject(ctx context.Context, arg CreateObjectParams) (CreateObjectRow, error) {
	row := q.db.QueryRowContext(ctx, createObject,
		arg.ID,
		arg.PrefixHash,
		arg.SizeBytes,
		arg.UploadStatus,
		arg.Metadata,
	)
	var i CreateObjectRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteObject = `-- name: DeleteObject :one
DELETE FROM objects WHERE id = ?
RETURNING id
`

func (q *Queries) DeleteObject(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteObject, id)
	err := row.Scan(&id)
	return id, err
}

const getObject = `-- name: GetObject :one
SELECT id, prefix_hash, size_bytes, upload_status, metadata, created_at, updated_at FROM objects WHERE id = ?
`

func (q *Queries) GetObject(ctx context.Context, id string) (Object, error) {
	row := q.db.QueryRowContext(ctx, getObject, id)
	var i Object
	err := row.Scan(
		&i.ID,
		&i.PrefixHash,
		&i.SizeBytes,
		&i.UploadStatus,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getObjectsByTag = `-- name: GetObjectsByTag :many
SELECT objects.id, objects.prefix_hash, objects.size_bytes, objects.upload_status, objects.metadata, objects.created_at, objects.updated_at
FROM objects
INNER JOIN object_tags ON object_tags.object_id = objects.id
WHERE object_tags.tag_hash = ?
`

func (q *Queries) GetObjectsByTag(ctx context.Context, tagHash string) ([]Object, error) {
	rows, err := q.db.QueryContext(ctx, getObjectsByTag, tagHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Object
	for rows.Next() {
		var i Object
		if err := rows.Scan(
			&i.ID,
			&i.PrefixHash,
			&i.SizeBytes,
			&i.UploadStatus,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectsByParent = `-- name: ListObjectsByParent :many
SELECT id, prefix_hash, size_bytes, upload_status, metadata, created_at, updated_at FROM objects WHERE prefix_hash = ?
`

func (q *Queries) ListObjectsByParent(ctx context.Context, prefixHash string) ([]Object, error) {
	rows, err := q.db.QueryContext(ctx, listObjectsByParent, prefixHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Object
	for rows.Next() {
		var i Object
		if err := rows.Scan(
			&i.ID,
			&i.PrefixHash,
			&i.SizeBytes,
			&i.UploadStatus,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateObject = `-- name: UpdateObject :one
UPDATE objects
SET
  prefix_hash = COALESCE(?2, prefix_hash),
  size_bytes = COALESCE(?3, size_bytes),
  metadata = COALESCE(?4, metadata),
  upload_status = COALESCE(?5, upload_status),
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, updated_at
`

type UpdateObjectParams struct {
	PrefixHash   sql.NullString `json:"prefix_hash"`
	SizeBytes    sql.NullInt64  `json:"size_bytes"`
	Metadata     []byte         `json:"metadata"`
	UploadStatus sql.NullString `json:"upload_status"`
	ID           string         `json:"id"`
}

type UpdateObjectRow struct {
	ID        string    `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateObject(ctx context.Context, arg UpdateObjectParams) (UpdateObjectRow, error) {
	row := q.db.QueryRowContext(ctx, updateObject,
		arg.PrefixHash,
		arg.SizeBytes,
		arg.Metadata,
		arg.UploadStatus,
		arg.ID,
	)
	var i UpdateObjectRow
	err := row.Scan(&i.ID, &i.UpdatedAt)
	return i, err
}

const updateStatus = `-- name: UpdateStatus :one
UPDATE objects
SET
  upload_status = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, updated_at
`

type UpdateStatusParams struct {
	UploadStatus string `json:"upload_status"`
	ID           string `json:"id"`
}

type UpdateStatusRow struct {
	ID        string    `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (UpdateStatusRow, error) {
	row := q.db.QueryRowContext(ctx, updateStatus, arg.UploadStatus, arg.ID)
	var i UpdateStatusRow
	err := row.Scan(&i.ID, &i.UpdatedAt)
	return i, err
}
