// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orbit.sql

package database

import (
	"context"
	"time"
)

const createOrbit = `-- name: CreateOrbit :one
INSERT INTO orbit (
  persona_id,
  public_key,
  metadata,
  created_at,
  updated_at
)
VALUES (
  ?,
  ?,
  ?,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
RETURNING persona_id, created_at
`

type CreateOrbitParams struct {
	PersonaID string `json:"persona_id"`
	PublicKey []byte `json:"public_key"`
	Metadata  []byte `json:"metadata"`
}

type CreateOrbitRow struct {
	PersonaID string    `json:"persona_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateOrbit(ctx context.Context, arg CreateOrbitParams) (CreateOrbitRow, error) {
	row := q.db.QueryRowContext(ctx, createOrbit, arg.PersonaID, arg.PublicKey, arg.Metadata)
	var i CreateOrbitRow
	err := row.Scan(&i.PersonaID, &i.CreatedAt)
	return i, err
}

const deleteOrbit = `-- name: DeleteOrbit :one
DELETE FROM orbit WHERE persona_id = ?
RETURNING persona_id
`

func (q *Queries) DeleteOrbit(ctx context.Context, personaID string) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteOrbit, personaID)
	var persona_id string
	err := row.Scan(&persona_id)
	return persona_id, err
}

const getOrbit = `-- name: GetOrbit :one
SELECT persona_id, public_key, metadata, created_at, updated_at FROM orbit WHERE persona_id = ?
`

func (q *Queries) GetOrbit(ctx context.Context, personaID string) (Orbit, error) {
	row := q.db.QueryRowContext(ctx, getOrbit, personaID)
	var i Orbit
	err := row.Scan(
		&i.PersonaID,
		&i.PublicKey,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrbitMetadata = `-- name: UpdateOrbitMetadata :one
UPDATE orbit
SET
  metadata = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE persona_id = ?
RETURNING persona_id, updated_at
`

type UpdateOrbitMetadataParams struct {
	Metadata  []byte `json:"metadata"`
	PersonaID string `json:"persona_id"`
}

type UpdateOrbitMetadataRow struct {
	PersonaID string    `json:"persona_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateOrbitMetadata(ctx context.Context, arg UpdateOrbitMetadataParams) (UpdateOrbitMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, updateOrbitMetadata, arg.Metadata, arg.PersonaID)
	var i UpdateOrbitMetadataRow
	err := row.Scan(&i.PersonaID, &i.UpdatedAt)
	return i, err
}
