// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orbit.sql

package database

import (
	"context"
	"time"
)

const addToOrbit = `-- name: AddToOrbit :one
INSERT INTO orbit (
  persona_id,
  signing_key,
  exchange_key,
  metadata,
  created_at,
  updated_at
)
VALUES (
  ?,
  ?,
  ?,
  ?,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
RETURNING persona_id, created_at
`

type AddToOrbitParams struct {
	PersonaID   string `json:"persona_id"`
	SigningKey  []byte `json:"signing_key"`
	ExchangeKey []byte `json:"exchange_key"`
	Metadata    []byte `json:"metadata"`
}

type AddToOrbitRow struct {
	PersonaID string    `json:"persona_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) AddToOrbit(ctx context.Context, arg AddToOrbitParams) (AddToOrbitRow, error) {
	row := q.db.QueryRowContext(ctx, addToOrbit,
		arg.PersonaID,
		arg.SigningKey,
		arg.ExchangeKey,
		arg.Metadata,
	)
	var i AddToOrbitRow
	err := row.Scan(&i.PersonaID, &i.CreatedAt)
	return i, err
}

const deleteFromOrbit = `-- name: DeleteFromOrbit :one
DELETE FROM orbit WHERE persona_id = ?
RETURNING persona_id
`

func (q *Queries) DeleteFromOrbit(ctx context.Context, personaID string) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteFromOrbit, personaID)
	var persona_id string
	err := row.Scan(&persona_id)
	return persona_id, err
}

const getFromOrbit = `-- name: GetFromOrbit :one
SELECT persona_id, signing_key, exchange_key, metadata, created_at, updated_at FROM orbit WHERE persona_id = ?
`

func (q *Queries) GetFromOrbit(ctx context.Context, personaID string) (Orbit, error) {
	row := q.db.QueryRowContext(ctx, getFromOrbit, personaID)
	var i Orbit
	err := row.Scan(
		&i.PersonaID,
		&i.SigningKey,
		&i.ExchangeKey,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrbitList = `-- name: GetOrbitList :many
SELECT persona_id, signing_key, exchange_key, metadata, created_at, updated_at FROM orbit
`

func (q *Queries) GetOrbitList(ctx context.Context) ([]Orbit, error) {
	rows, err := q.db.QueryContext(ctx, getOrbitList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Orbit
	for rows.Next() {
		var i Orbit
		if err := rows.Scan(
			&i.PersonaID,
			&i.SigningKey,
			&i.ExchangeKey,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrbitMetadata = `-- name: UpdateOrbitMetadata :one
UPDATE orbit
SET
  metadata = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE persona_id = ?
RETURNING persona_id, updated_at
`

type UpdateOrbitMetadataParams struct {
	Metadata  []byte `json:"metadata"`
	PersonaID string `json:"persona_id"`
}

type UpdateOrbitMetadataRow struct {
	PersonaID string    `json:"persona_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateOrbitMetadata(ctx context.Context, arg UpdateOrbitMetadataParams) (UpdateOrbitMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, updateOrbitMetadata, arg.Metadata, arg.PersonaID)
	var i UpdateOrbitMetadataRow
	err := row.Scan(&i.PersonaID, &i.UpdatedAt)
	return i, err
}
