// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	AddUFOTag(ctx context.Context, arg AddUFOTagParams) (string, error)
	CreateUFO(ctx context.Context, arg CreateUFOParams) (CreateUFORow, error)
	DeleteStaleRequests(ctx context.Context) error
	DeleteUFO(ctx context.Context, id string) (DeleteUFORow, error)
	DeleteUFOTags(ctx context.Context, ufoID string) error
	GetRequestByID(ctx context.Context, id string) (Request, error)
	GetTagsForUFO(ctx context.Context, ufoID string) ([]UfoTag, error)
	GetUFO(ctx context.Context, id string) (Ufo, error)
	GetUFOsByParent(ctx context.Context, prefixHash string) ([]Ufo, error)
	GetUFOsByTag(ctx context.Context, tagHash string) ([]Ufo, error)
	NewRequest(ctx context.Context, id string) error
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) (UpdateStatusRow, error)
	UpdateUFO(ctx context.Context, arg UpdateUFOParams) (UpdateUFORow, error)
}

var _ Querier = (*Queries)(nil)
