// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	AddObjectTag(ctx context.Context, arg AddObjectTagParams) error
	CreateObject(ctx context.Context, arg CreateObjectParams) error
	DeleteObject(ctx context.Context, id string) error
	DeleteObjectTags(ctx context.Context, objectID string) error
	DeleteStaleRequests(ctx context.Context) error
	GetObject(ctx context.Context, id string) (Object, error)
	GetObjectsByTag(ctx context.Context, tagHash string) ([]Object, error)
	GetRequestByID(ctx context.Context, id string) (Request, error)
	GetTagsForObject(ctx context.Context, objectID string) ([]ObjectTag, error)
	ListObjectsByParent(ctx context.Context, prefixHash string) ([]Object, error)
	NewRequest(ctx context.Context, id string) error
	UpdateObject(ctx context.Context, arg UpdateObjectParams) error
}

var _ Querier = (*Queries)(nil)
