// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package database

import (
	"context"
)

const deleteStaleRequests = `-- name: DeleteStaleRequests :exec
DELETE FROM requests WHERE created_at < DATETIME('now', '-5 minutes')
`

func (q *Queries) DeleteStaleRequests(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteStaleRequests)
	return err
}

const getRequestByID = `-- name: GetRequestByID :one
SELECT id, created_at FROM requests WHERE id = ?
`

func (q *Queries) GetRequestByID(ctx context.Context, id string) (Request, error) {
	row := q.db.QueryRowContext(ctx, getRequestByID, id)
	var i Request
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const newRequest = `-- name: NewRequest :exec
INSERT INTO requests (id)
VALUES (?)
`

func (q *Queries) NewRequest(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, newRequest, id)
	return err
}
