// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ufo_tags.sql

package database

import (
	"context"
)

const addUFOTag = `-- name: AddUFOTag :exec
INSERT OR IGNORE INTO ufo_tags (ufo_id, tag_hash)
VALUES (?, ?)
`

type AddUFOTagParams struct {
	UfoID   string `json:"ufo_id"`
	TagHash string `json:"tag_hash"`
}

func (q *Queries) AddUFOTag(ctx context.Context, arg AddUFOTagParams) error {
	_, err := q.db.ExecContext(ctx, addUFOTag, arg.UfoID, arg.TagHash)
	return err
}

const deleteUFOTags = `-- name: DeleteUFOTags :exec
DELETE FROM ufo_tags WHERE ufo_id = ?
`

func (q *Queries) DeleteUFOTags(ctx context.Context, ufoID string) error {
	_, err := q.db.ExecContext(ctx, deleteUFOTags, ufoID)
	return err
}

const getTagsForUFO = `-- name: GetTagsForUFO :many
SELECT ufo_id, tag_hash FROM ufo_tags WHERE ufo_id = ?
`

func (q *Queries) GetTagsForUFO(ctx context.Context, ufoID string) ([]UfoTag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsForUFO, ufoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UfoTag
	for rows.Next() {
		var i UfoTag
		if err := rows.Scan(&i.UfoID, &i.TagHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
