// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ufo_access.sql

package database

import (
	"context"
)

const addUFOAccess = `-- name: AddUFOAccess :one
INSERT OR IGNORE INTO ufo_access (ufo_id, persona_id, wrapped_key)
VALUES (
  ?,
  ?,
  ?
)
RETURNING ufo_id
`

type AddUFOAccessParams struct {
	UfoID      string `json:"ufo_id"`
	PersonaID  string `json:"persona_id"`
	WrappedKey []byte `json:"wrapped_key"`
}

func (q *Queries) AddUFOAccess(ctx context.Context, arg AddUFOAccessParams) (string, error) {
	row := q.db.QueryRowContext(ctx, addUFOAccess, arg.UfoID, arg.PersonaID, arg.WrappedKey)
	var ufo_id string
	err := row.Scan(&ufo_id)
	return ufo_id, err
}

const deleteUFOAccess = `-- name: DeleteUFOAccess :exec
DELETE FROM ufo_access WHERE ufo_id = ?
`

func (q *Queries) DeleteUFOAccess(ctx context.Context, ufoID string) error {
	_, err := q.db.ExecContext(ctx, deleteUFOAccess, ufoID)
	return err
}

const getKeybyUFOIDAndPersonaID = `-- name: GetKeybyUFOIDAndPersonaID :one
SELECT wrapped_key FROM ufo_access
WHERE ufo_id = ? AND persona_id = ?
`

type GetKeybyUFOIDAndPersonaIDParams struct {
	UfoID     string `json:"ufo_id"`
	PersonaID string `json:"persona_id"`
}

func (q *Queries) GetKeybyUFOIDAndPersonaID(ctx context.Context, arg GetKeybyUFOIDAndPersonaIDParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getKeybyUFOIDAndPersonaID, arg.UfoID, arg.PersonaID)
	var wrapped_key []byte
	err := row.Scan(&wrapped_key)
	return wrapped_key, err
}

const getUFOAccessForUser = `-- name: GetUFOAccessForUser :one
SELECT COUNT(*) FROM ufo_access
WHERE ufo_id = ? AND persona_id = ?
`

type GetUFOAccessForUserParams struct {
	UfoID     string `json:"ufo_id"`
	PersonaID string `json:"persona_id"`
}

func (q *Queries) GetUFOAccessForUser(ctx context.Context, arg GetUFOAccessForUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUFOAccessForUser, arg.UfoID, arg.PersonaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUsersForUFO = `-- name: GetUsersForUFO :many
SELECT ufo_id, persona_id, wrapped_key FROM ufo_access WHERE ufo_id = ?
`

func (q *Queries) GetUsersForUFO(ctx context.Context, ufoID string) ([]UfoAccess, error) {
	rows, err := q.db.QueryContext(ctx, getUsersForUFO, ufoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UfoAccess
	for rows.Next() {
		var i UfoAccess
		if err := rows.Scan(&i.UfoID, &i.PersonaID, &i.WrappedKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
