// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ufos.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createUFO = `-- name: CreateUFO :one
INSERT INTO ufos (
  id,
  name_hash,
  prefix_hash,
  size_bytes,
  upload_status,
  metadata,
  created_at,
  updated_at
)
VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
RETURNING id, created_at
`

type CreateUFOParams struct {
	ID           string `json:"id"`
	NameHash     string `json:"name_hash"`
	PrefixHash   string `json:"prefix_hash"`
	SizeBytes    int64  `json:"size_bytes"`
	UploadStatus string `json:"upload_status"`
	Metadata     []byte `json:"metadata"`
}

type CreateUFORow struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateUFO(ctx context.Context, arg CreateUFOParams) (CreateUFORow, error) {
	row := q.db.QueryRowContext(ctx, createUFO,
		arg.ID,
		arg.NameHash,
		arg.PrefixHash,
		arg.SizeBytes,
		arg.UploadStatus,
		arg.Metadata,
	)
	var i CreateUFORow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createUFOFolder = `-- name: CreateUFOFolder :one
INSERT INTO ufos (
  id,
  name_hash,
  prefix_hash,
  size_bytes,
  upload_status,
  metadata,
  created_at,
  updated_at
)
VALUES (
  ?,
  ?,
  ?,
  -1,
  "active",
  ?,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT(name_hash, prefix_hash) DO UPDATE SET
    updated_at = EXCLUDED.updated_at
RETURNING id, created_at, updated_at
`

type CreateUFOFolderParams struct {
	ID         string `json:"id"`
	NameHash   string `json:"name_hash"`
	PrefixHash string `json:"prefix_hash"`
	Metadata   []byte `json:"metadata"`
}

type CreateUFOFolderRow struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateUFOFolder(ctx context.Context, arg CreateUFOFolderParams) (CreateUFOFolderRow, error) {
	row := q.db.QueryRowContext(ctx, createUFOFolder,
		arg.ID,
		arg.NameHash,
		arg.PrefixHash,
		arg.Metadata,
	)
	var i CreateUFOFolderRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteUFO = `-- name: DeleteUFO :one
DELETE FROM ufos WHERE id = ?
RETURNING id, size_bytes
`

type DeleteUFORow struct {
	ID        string `json:"id"`
	SizeBytes int64  `json:"size_bytes"`
}

func (q *Queries) DeleteUFO(ctx context.Context, id string) (DeleteUFORow, error) {
	row := q.db.QueryRowContext(ctx, deleteUFO, id)
	var i DeleteUFORow
	err := row.Scan(&i.ID, &i.SizeBytes)
	return i, err
}

const getUFO = `-- name: GetUFO :one
SELECT id, name_hash, prefix_hash, size_bytes, upload_status, metadata, created_at, updated_at FROM ufos WHERE id = ?
`

func (q *Queries) GetUFO(ctx context.Context, id string) (Ufo, error) {
	row := q.db.QueryRowContext(ctx, getUFO, id)
	var i Ufo
	err := row.Scan(
		&i.ID,
		&i.NameHash,
		&i.PrefixHash,
		&i.SizeBytes,
		&i.UploadStatus,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUFOByNameAndParent = `-- name: GetUFOByNameAndParent :one
SELECT id, name_hash, prefix_hash, size_bytes, upload_status, metadata, created_at, updated_at FROM ufos WHERE name_hash = ? AND prefix_hash = ?
`

type GetUFOByNameAndParentParams struct {
	NameHash   string `json:"name_hash"`
	PrefixHash string `json:"prefix_hash"`
}

func (q *Queries) GetUFOByNameAndParent(ctx context.Context, arg GetUFOByNameAndParentParams) (Ufo, error) {
	row := q.db.QueryRowContext(ctx, getUFOByNameAndParent, arg.NameHash, arg.PrefixHash)
	var i Ufo
	err := row.Scan(
		&i.ID,
		&i.NameHash,
		&i.PrefixHash,
		&i.SizeBytes,
		&i.UploadStatus,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUFOsByParent = `-- name: GetUFOsByParent :many
SELECT id, name_hash, prefix_hash, size_bytes, upload_status, metadata, created_at, updated_at FROM ufos WHERE prefix_hash = ?
`

func (q *Queries) GetUFOsByParent(ctx context.Context, prefixHash string) ([]Ufo, error) {
	rows, err := q.db.QueryContext(ctx, getUFOsByParent, prefixHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ufo
	for rows.Next() {
		var i Ufo
		if err := rows.Scan(
			&i.ID,
			&i.NameHash,
			&i.PrefixHash,
			&i.SizeBytes,
			&i.UploadStatus,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUFOsByTag = `-- name: GetUFOsByTag :many
SELECT ufos.id, ufos.name_hash, ufos.prefix_hash, ufos.size_bytes, ufos.upload_status, ufos.metadata, ufos.created_at, ufos.updated_at
FROM ufos
INNER JOIN ufo_tags ON ufo_tags.ufo_id = ufos.id
WHERE ufo_tags.tag_hash = ?
`

func (q *Queries) GetUFOsByTag(ctx context.Context, tagHash string) ([]Ufo, error) {
	rows, err := q.db.QueryContext(ctx, getUFOsByTag, tagHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ufo
	for rows.Next() {
		var i Ufo
		if err := rows.Scan(
			&i.ID,
			&i.NameHash,
			&i.PrefixHash,
			&i.SizeBytes,
			&i.UploadStatus,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStatus = `-- name: UpdateStatus :one
UPDATE ufos
SET
  upload_status = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, upload_status
`

type UpdateStatusParams struct {
	UploadStatus string `json:"upload_status"`
	ID           string `json:"id"`
}

type UpdateStatusRow struct {
	ID           string `json:"id"`
	UploadStatus string `json:"upload_status"`
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (UpdateStatusRow, error) {
	row := q.db.QueryRowContext(ctx, updateStatus, arg.UploadStatus, arg.ID)
	var i UpdateStatusRow
	err := row.Scan(&i.ID, &i.UploadStatus)
	return i, err
}

const updateUFO = `-- name: UpdateUFO :one
UPDATE ufos
SET
  name_hash = COALESCE(?2, name_hash),
  prefix_hash = COALESCE(?3, prefix_hash),
  size_bytes = COALESCE(?4, size_bytes),
  metadata = COALESCE(?5, metadata),
  upload_status = COALESCE(?6, upload_status),
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, updated_at
`

type UpdateUFOParams struct {
	NameHash     sql.NullString `json:"name_hash"`
	PrefixHash   sql.NullString `json:"prefix_hash"`
	SizeBytes    sql.NullInt64  `json:"size_bytes"`
	Metadata     []byte         `json:"metadata"`
	UploadStatus sql.NullString `json:"upload_status"`
	ID           string         `json:"id"`
}

type UpdateUFORow struct {
	ID        string    `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateUFO(ctx context.Context, arg UpdateUFOParams) (UpdateUFORow, error) {
	row := q.db.QueryRowContext(ctx, updateUFO,
		arg.NameHash,
		arg.PrefixHash,
		arg.SizeBytes,
		arg.Metadata,
		arg.UploadStatus,
		arg.ID,
	)
	var i UpdateUFORow
	err := row.Scan(&i.ID, &i.UpdatedAt)
	return i, err
}
